### ISSUE TITLE
User interface-Connectivity button

### ISSUE THREAD

**Issue by ghost** [DIT112-V20/group-01#21]
**User story:**
As a user, I want to be able to connect the app with the car.

**Acceptance Criteria:**
A button on the app that, when pressed by the user, a connection to the car is established.

**Comment by platisd** [comment]
Why was this story closed?

**Comment by ghost** [comment]
> Why was this story closed?

We decided not to go with a connectivity button in the app, so this wasn't a part of the code, and we didn't want to keep the issue open.

**Comment by platisd** [comment]
Then please make this decision somehow visible :+1:
