### ISSUE TITLE
Overall improved UI

### ISSUE THREAD

**Issue by ghost** [DIT112-V20/group-01#44]
**User Story:**
As a user, I want to have a clean and nice looking user interface design for the the application.

**Acceptance Criteria:**
The user will have a welcome screen with the option to choose between manual control and autonomous driving, once the manual control is pressed, the user goes to a screen where he can control the direction and speed of the car, if the autonomous driving button is pressed, the user goes to another screen where he can start/stop the driving, and receive info about the distance covered. Both screens include the option to go back to the starting screen.

**Comment by platisd** [comment]
> Improvements will be made to the current UI.

This is too vague to be an acceptance criterion. What is an improvement for me is not necessarily the same for you.

**Comment by ghost** [comment]
@platisd check it now :)

**Comment by platisd** [comment]
Much better :+1:
