### ISSUE TITLE
Basic obstacle avoidance does not work

### ISSUE THREAD

**Issue by platisd** [DIT112-V20/group-01#9]
You basic obstacle avoidance sketch is logically flawed and if I would guess you did not even try it out, at least using this specific sketch. How can I tell? Secret. :zipper_mouth_face: But if you look closely enough (or try it out on the car) you will also realize it.

The problem with the logic is that when there is no obstacle detected, the sensor will return 0. Therefore your car will stop even if there is no obstacle in front of it.

**Comment by ghost** [comment]
@platisd thank you for pointing it out. I think I fixed the logical error in the code, but we're still not able to try it out with the car. We're having some issues with the hardware. My teammate sent you an email about that earlier today. We'll try it as soon as we can.

**Comment by platisd** [comment]
In regards to the code itself, let's discuss it in #10.
Other than that, please not wait for problems (e.g. with hardware) to solve themselves out but instead take actions (e.g. contact me).
